### ISSUE TITLE
微信登录问题

### ISSUE THREAD

**Issue by juckknife** [AlloVince/EvaOAuth#6]
你好 我在使用微信登录的时候遇到了问题

https://open.weixin.qq.com/connect/qrconnect?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect

微信登录中 client_id 变成了 appid  有没有办法在外层调用的时候控制authorizeUrl最终拼接成上面那种形式

**Comment by AlloVince** [comment]
在版本1.0.x可以这样处理，略tricky

``` php
$service->getEmitter()->on('beforeAuthorize', function(\Eva\EvaOAuth\Events\BeforeAuthorize $event) {
    $uri = str_replace('client_id', 'app_id', $event->getUri());
    header("Location: $uri");
    exit;
});
```

之后版本中会考虑authorizeUri的替换问题
