### ISSUE TITLE
如何增加淘宝千牛的支持呢？

### ISSUE THREAD

**Issue by chenge** [AlloVince/EvaOAuth#7]
也就是增加一个， 还是有别的办法么？

我尝试了一下，似乎不那么容易。  千牛是oauth2， 先取得code，第二次获得token。

谢谢， 感觉EvaOAuth不错。

**Comment by AlloVince** [comment]
新增provider可以参考文档
https://github.com/AlloVince/EvaOAuth#providers

如果provider有一些非标准部分，可以参考这个issue https://github.com/AlloVince/EvaOAuth/issues/6
通过事件修改或替换部分参数
